version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.39
    - 14.14.41
    - 14.14.42
  - dependency-name: fastify
    versions:
    - 3.13.0
    - 3.14.0
    - 3.14.2
  - dependency-name: "@types/sharp"
    versions:
    - 0.27.2
    - 0.28.0
  - dependency-name: sharp
    versions:
    - 0.26.3
    - 0.28.0
    - 0.28.1
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: html-entities
    versions:
    - 2.1.0
    - 2.1.1
    - 2.3.1
    - 2.3.2
  - dependency-name: "@types/js-yaml"
    versions:
    - 4.0.0
  - dependency-name: is-svg
    versions:
    - 4.2.2
    - 4.3.1
  - dependency-name: probe-image-size
    versions:
    - 7.0.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
  - dependency-name: "@types/express"
    versions:
    - 4.17.11
